### ISSUE TITLE
Rspack bundler support

### ISSUE THREAD

**Issue by ild0tt0re** [react-loadable/revised#9]
We were almost able to complete the transition from **Webpack5** to the faster Rust-based web bundler [**Rspack**](https://www.rspack.dev/) except for an error due to this plugin: `error[internal]: TypeError: compilation.chunkGroups is not iterable`

```
error[internal]: TypeError: compilation.chunkGroups is not iterable
    at buildManifest (/Users/myuser/dev/my.project/node_modules/@react-loadable/revised/webpack.ts:49:39)
    at emit (/Users/myuser/dev/my.project/node_modules/@react-loadable/revised/webpack.ts:122:22)
    at eval (eval at create (/Users/myuser/dev/my.project/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:17:1)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/Users/myuser/dev/my.project/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:6:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/Users/myuser/dev/my.project/node_modules/tapable/lib/Hook.js:22:14)
    at Compiler._Compiler_emit (/Users/myuser/dev/my.project/node_modules/@rspack/core/dist/Compiler.js:769:27)
```

would it be possible to make this plugin compatible with rspack?

**Comment by tranvansang** [comment]
Could you try raising issue in Rspack repo?
